spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root # mysql username
    password: devfest2021  # mysql password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test # jdbc:mysql://<mysql-server-address>:<port>/<database>
